{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nats-ui.fullname" . }}
  labels:
    {{- include "nats-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  NATS_PASS: {{ .Values.secrets.natsPass | quote }}
  ADMIN_PASS: {{ .Values.secrets.adminPass | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  {{- if .Values.oauth2.google.clientID }}
  GOOGLE_CLIENT_ID: {{ .Values.oauth2.google.clientID | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.oauth2.google.clientSecret | quote }}
  {{- end }}
  {{- if .Values.oauth2.github.clientID }}
  GITHUB_CLIENT_ID: {{ .Values.oauth2.github.clientID | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.oauth2.github.clientSecret | quote }}
  {{- end }}
  {{- if .Values.oauth2.keycloak.clientID }}
  KEYCLOAK_CLIENT_ID: {{ .Values.oauth2.keycloak.clientID | quote }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.oauth2.keycloak.clientSecret | quote }}
  {{- end }}
  {{- if .Values.oauth2.oidc.clientID }}
  OIDC_CLIENT_ID: {{ .Values.oauth2.oidc.clientID | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.oauth2.oidc.clientSecret | quote }}
  {{- end }}
{{- end }}
